version: '3.7'
services:
    postgres:
        image: postgres:10.5
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          - ./scripts/create.sql:/docker-entrypoint-initdb.d/create.sql
          - ./scripts/insert.sql:/docker-entrypoint-initdb.d/insert.sql
